### ISSUE TITLE
 Could you help me, please

### ISSUE THREAD

**Issue by BreimmGer** [danielfelipesartorio/Degas#1]
Hi Daniel
I have no questions
Could you please help me to create the foe bot (FoBJS_Release )

**Comment by danielfelipesartorio** [comment]
Sure.
You want to change the code or just have the bot working?
Here is the download link for the working bot
[Here](https://mega.nz/file/lFgm3ARb#le7VBBQJ5Awk5yuMAqSlmDuxprj0jPGJNt1d8pektho)

**Comment by BreimmGer** [comment]
Hi
that it works
since I have no plan to code

**Comment by BreimmGer** [comment]
thank you

**Comment by BreimmGer** [comment]
Hi Daniel
He stops at login and does not continue

**Comment by danielfelipesartorio** [comment]
There was an update to the game, and it broke the bot.
I tried to fix it, and sent it to the th3c0d3r, he needs to validate the fix and release a new oficial version

**Comment by BreimmGer** [comment]
Ah ok thanx for the info 
Can you let me know when it works again

**Comment by BreimmGer** [comment]
Hi Daniel
a new version is already out

**Comment by danielfelipesartorio** [comment]
[here](https://github.com/danielfelipesartorio/FoBJS/tree/add-dark-mode/release-builds)
For future problems, please open an issue on the correct project.
I'm closing this issue
